### PR TITLE
Feature: sizes customizing

### PR DESCRIPTION
**Pull request by siarhei-epam**
Adding size tokens to components

### CODE REVIEW

**Review by AlekseyManetov — CHANGES_REQUESTED** [review]

**Comment by NatalliaAlieva** [comment]
The size of the inner circle in the radio button for size 12 differs between Figma and Dev. Awaiting a solution from the design team. @DzmitryTrubchyk

**Comment by NatalliaAlieva** [comment]
Error "can't resolve" appeared in property explorer for Icon container
Screenshot 2024-06-24 at 11 45 41

**Comment by DzmitryTrubchyk** [comment]
> The size of the inner circle in the radio button for size 12 differs between Figma and Dev. Awaiting a solution from the design team. @DzmitryTrubchyk Screenshot 2024-06-19 at 14 57 11

Let's leave as on frontend now, we will fix in Figma

**Comment by NatalliaAlieva** [comment]
> The size of the inner circle in the radio button for size 12 differs between Figma and Dev. Awaiting a solution from the design team. @DzmitryTrubchyk Screenshot 2024-06-19 at 14 57 11

It was decided to align the Figma design with the current state of the front end.

**Comment by NatalliaAlieva** [comment]
Released in 5.8.2 ver.

**Pull request merged**
